spring.application.name=sistemainscripcion

server.port=8080

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:inscripciondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Consola H2 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true

# AWS S3
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.sessionToken=${AWS_SESSION_TOKEN}
aws.region=${AWS_REGION}
aws.bucketName=bucketinscripciones

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://duocazureb2ctenant.b2clogin.com/duocazureb2ctenant.onmicrosoft.com/B2C_1_DuocDemoAzure_registro_login/v2.0/